name: Defacto Stok Botu
on:
  schedule:
    - cron: '*/5 * * * *' # Her 5 dakikada bir otomatik çalışır
  workflow_dispatch: # İstersen elle de tetikleyebilmeni sağlar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v3
      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Kütüphaneleri Yükle
        run: pip install requests selenium
      - name: Botu Çalıştır
        env:
          TELE_TOKEN: ${{ secrets.TELE_TOKEN }}
          TELE_CHAT_ID: ${{ secrets.TELE_CHAT_ID }}
        run: python main.py
